--Họ Tên:Trần Anh Hào
--MSSV:23520449
CREATE DATABASE QLBH

USE QLBANHANG

CREATE TABLE KHACHHANG(
	MAKH char(4) PRIMARY KEY,
	HOTEN varchar(40),
	DIACHI varchar(50),
	SDT varchar(20),
	NGSINH smalldatetime,
	DOANHSO money,
	NGDK smalldatetime,
);

CREATE TABLE NHANVIEN(
	MANV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	NGVL smalldatetime,
	SDT varchar(20),
);

CREATE TABLE SANPHAM(
	MASP char(4) PRIMARY KEY,
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar(20),
	GIA money,
);

CREATE TABLE HOADON(
	SOHD int PRIMARY KEY,
	NGHD smalldatetime,
	MAKH char(4) REFERENCES KHACHHANG(MAKH),
	MANV char(4) REFERENCES NHANVIEN(MANV),
	TRIGIA money,
);

CREATE TABLE CTHD(
	SOHD int REFERENCES HOADON(SOHD),
	MASP char(4) REFERENCES SANPHAM(MASP),
	PRIMARY KEY (SOHD, MASP),
);





ALTER TABLE SANPHAM
ADD GHICHU varchar(20)

ALTER TABLE KHACHHANG
ADD LOAIKH tinyint 

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU varchar(100)

ALTER TABLE SANPHAM
DROP COLUMN GHICHU

ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH varchar(12)
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECKLOAIKH CHECK( LOAIKH IN ('Vang lai', 'Thuong xuyen', 'Vip'))

ALTER TABLE SANPHAM ADD CONSTRAINT CHECKSP CHECK(DVT IN('cay', 'hop', 'cai', 'quyen', 'chuc'))

ALTER TABLE SANPHAM ADD CONSTRAINT CHECKGIA CHECK(GIA>=500)

ALTER TABLE HOADON ADD CONSTRAINT CHECKSOSPMUA CHECK(TRIGIA>0)

ALTER TABLE KHACHHANG ADD CONSTRAINT CHECKNGAYDK CHECK(NGDK>=NGSINH)












